CREATE TABLE COMPANIES (
  HANDLE VARCHAR(25) PRIMARY KEY CHECK (HANDLE = LOWER(HANDLE)),
  NAME TEXT UNIQUE NOT NULL,
  NUM_EMPLOYEES INTEGER CHECK (NUM_EMPLOYEES >= 0),
  DESCRIPTION TEXT NOT NULL,
  LOGO_URL TEXT
);

CREATE TABLE USERS (
  USERNAME VARCHAR(25) PRIMARY KEY,
  PASSWORD TEXT NOT NULL,
  FIRST_NAME TEXT NOT NULL,
  LAST_NAME TEXT NOT NULL,
  EMAIL TEXT NOT NULL CHECK (POSITION('@' IN EMAIL) > 1),
  IS_ADMIN BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE JOBS (
  ID SERIAL PRIMARY KEY,
  TITLE TEXT NOT NULL,
  SALARY INTEGER CHECK (SALARY >= 0),
  EQUITY NUMERIC CHECK (EQUITY <= 1.0),
  COMPANY_HANDLE VARCHAR(25) NOT NULL REFERENCES COMPANIES ON DELETE CASCADE
);

CREATE TABLE APPLICATIONS (
  USERNAME VARCHAR(25) REFERENCES USERS ON DELETE CASCADE,
  JOB_ID INTEGER REFERENCES JOBS ON DELETE CASCADE,
  PRIMARY KEY (USERNAME, JOB_ID)
);